SELECT * FROM DOCTOR_MASTER ORDER BY DOCTOR_ID;
SELECT * FROM PATIENT_MASTER ORDER BY PATIENT_ID;
SELECT * FROM DOCTOR_AVAILABILITY ORDER BY AVAILABILITY_ID;
SELECT * FROM APPOINTMENT ORDER BY APPOINTMENT_ID;
SELECT * FROM CONSULTATION ORDER BY CONSULTATION_ID;
SELECT * FROM BILLING ORDER BY BILL_ID;
